### ISSUE TITLE
w4sp-lab Installation error

### ISSUE THREAD

**Issue by ghcjsnb** [Grigorii-Voroshnin/w4sp-lab#1]
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-main/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
The command '/bin/sh -c git clone https://gitlab.cern.ch/smm-rme/pysmbclient.git' returned a non-zero code: 128
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 102, in docker_build
    r('docker build -t $image_name $image')
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']' returned non-zero exit status 128.

**Comment by Huang2077** [comment]
I already solved the your problem. please check https://medium.com/@huangjingtao2077/setting-up-the-w4sp-lab-in-2022-a3be14241d87

**Comment by tfsiqueira** [comment]
> I already solved the your problem. please check https://medium.com/@huangjingtao2077/setting-up-the-w4sp-lab-in-2022-a3be14241d87

Hello, now it is breaking a few lines above. When are you going to install scapy. Any suggestions on how it can be fixed?

```
/home/w4sp-lab/Downloads/w4sp-lab-main/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
['docker', 'build', '-t', 'w4sp/labs:wireless', 'wireless']
['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
The command '/bin/sh -c cd scapy && python setup.py install' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 102, in docker_build
    r('docker build -t $image_name $image')
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']' returned non-zero exit status 1.
```

**Comment by enokaya** [comment]
> > I already solved the your problem. please check https://medium.com/@huangjingtao2077/setting-up-the-w4sp-lab-in-2022-a3be14241d87
> 
> Hello, now it is breaking a few lines above. When are you going to install scapy. Any suggestions on how it can be fixed?
> 
> ```
> /home/w4sp-lab/Downloads/w4sp-lab-main/images
> ['docker', 'build', '-t', 'w4sp/labs:base', 'base']
> ['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
> ['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
> ['docker', 'build', '-t', 'w4sp/labs:wireless', 'wireless']
> ['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
> ['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
> The command '/bin/sh -c cd scapy && python setup.py install' returned a non-zero code: 1
> Traceback (most recent call last):
>   File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_webapp.py", line 500, in <module>
>     w4sp.docker_build('images/')
>   File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 102, in docker_build
>     r('docker build -t $image_name $image')
>   File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 83, in r
>     return subprocess.check_output(cmd)
>   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']' returned non-zero exit status 1.
> ```

Sorry for responding months later, but maybe it will help others:
I fixed this by adding `git checkout tags/v2.5.0` to the RUN command in the Dockerfile file for the victims-VM.
1. go to the victims folder `cd images/victims`
2. open the Dockerfile in your prefered editor
3. find the line that starts with `RUN cd scapy` and replace it with `RUN cd scapy && git checkout tags/v2.5.0 && python setup.py install`
4. save and rerun `w4sp_webapp.py`

This is because scapy v2.5.0 is actually the last scapy release that supports Python 2

**Comment by mohankossie** [comment]
['which', 'dumpcap']
['getcap', b'/usr/bin/dumpcap']
[*] Error, capabilities not set correctly on dumpcap, setting capabilities
['setcap', '-r', b'/usr/bin/dumpcap']
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1.

**Comment by Grigorii-Voroshnin** [comment]
Bugs fixed and tested
